@startuml
skinparam dpi 300
left to right direction

frame client {
      card clinet1
      card client2
      card client3
}

frame router {
      label "router converts the udp connection\nto long connection in the application"
      agent router1
      agent router2
      agent router3
}

frame connection {
      card connection1
      card connection2
      card connection3
}

clinet1 .[#red].> router1
client2 .[#blue].> router1
client3 ..> router2
client3 ..> router3

router1 -[#red]-> connection1 : client1
router1 -[#blue]-> connection2 : client2
router2 --> connection3 : client3
router3 --> connection3 : client3

note bottom of router1
different clients use the same UDP channel,e.g NAT
endnote


note right of router
router2 and router3 are multiple channels used by a client,e.g LB
endnote

@enduml
