#!/bin/sh
# -*- tab-width:4;indent-tabs-mode:nil -*-
# ex: ts=4 sw=4 et

COMMAND_PREFIX="erl -pa ebin -pa ../../ebin -pa ../../deps/*/ebin -config app -s tcp_window main 5000"

case "$1" in
    sync)
        $COMMAND_PREFIX sync
        ;;
    async)
        $COMMAND_PREFIX async
        ;;
    async_force)
        $COMMAND_PREFIX async_force
        ;;
    async_nosuspend)
        $COMMAND_PREFIX async_nosuspend
        ;;
    *)
        echo "./run sync | async | async_force | async_nosuspend"
        exit 1
        ;;
esac

