name: Run test case

on: [pull_request]

jobs:

    run_test_case:

        runs-on: ubuntu-latest

        strategy:
          fail-fast: false
          matrix:
            otp:
              - erlang:27
              - erlang:26
              - erlang:25

        container:
            image: ${{ matrix.otp }}

        steps:
        - uses: actions/checkout@v4
        - name: Code dialyzer
          run: |
            make xref
            make dialyzer
        - name: Run tests
          run: |
            make eunit
            make ct
            make cover

    run_compose_tests:

        runs-on: ubuntu-latest

        strategy:
          fail-fast: false
          matrix:
            otp:
              - erlang:27
              - erlang:26
              - erlang:25

        steps:
        - uses: actions/checkout@v4
        - name: Run compose-based tests
          run: make ESOCKD_IMAGE_ERLANG=${{ matrix.otp }} ct-compose
